### ISSUE TITLE
Parsing error: Declaration or statement expected

### ISSUE THREAD

**Issue by peterennis** [iconify-design/iconify-react#10]
This:

![Capture636](https://user-images.githubusercontent.com/140737/61429180-17f85b80-a8da-11e9-9bad-7ebaa43418be.png)

Produces this result on save:

![Capture637](https://user-images.githubusercontent.com/140737/61429204-28a8d180-a8da-11e9-945a-c477a3d242f1.png)

```
import { Icon, InlineIcon } from "@iconify/react";
import trophy from "@iconify/icons-mdi-light/trophy";
import 1st - place - medal from "@iconify/icons-twemoji/1st-place-medal";
```

Related: https://github.com/iconify/iconify-react/issues/9

**Comment by cyberalien** [comment]
Same error as in issue you've linked - badly named variable. You can use any name you want.
