### ISSUE TITLE
Support for react native

### ISSUE THREAD

**Issue by bergersens** [iconify-design/iconify-react#11]
Is it possible to use it for react native?

Till now theres is the following error
`Invariant Violation: View config not found for name svg. Make sure to start component names with a capital letter.`

thanks.

**Comment by cyberalien** [comment]
There is no support for React Native yet. This component renders SVG using dangerouslySetInnerHTML to add SVG content, instead of splitting icon into multiple React components.

However proper support for React Native is in todo list. It will take a while to implement.

**Comment by jordymeow** [comment]
I am waiting for this too. I really love Iconify, and would love to continue using it for my React Native projects. Thank you :)

**Comment by oktaysenkan** [comment]
You can check my library **[react-native-iconify](https://github.com/oktaysenkan/react-native-iconify)**
