### ISSUE TITLE
[Browser Support] Iconify/React 1.1.1 is not  <= 11 compatible. 

### ISSUE THREAD

**Issue by bsolovij-ebsco** [iconify-design/iconify-react#13]
the npm distributed bundle `@iconify/react` is not presently being transpiled for backwards compatibility. 

An example of said incompatibility can be found here: 
https://github.com/iconify/iconify-react/blob/master/src/icon.js#L62

`Object.assign` is not compatible with IE less than Edge. Are there any plans to support older browsers like Iconify itself? Thanks in advance!

**Comment by cyberalien** [comment]
Thanks a lot for noticing and reporting. That's a very interesting issue that needs to be fixed.

For temporary solution I suggest to include `babel-polyfill` or copy polyfill from https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign

I'll find proper solution and will test it all in IE11 as soon as possible.

**Comment by cyberalien** [comment]
I've just published version 1.1.2. It should solve this issue.

Unfortunately currently I can't properly test it. Please check if it works in IE11 for you.

**Comment by bsolovij-ebsco** [comment]
Confirmed - that seems to have made it at least IE 11 compatible. Big kudos and thanks for super fast response

**Comment by bsolovij-ebsco** [comment]
here's the `dist` result - no more `Object.assign` but `.create` and then the `hasOwnProperty` song and dance :
![image](https://user-images.githubusercontent.com/58519682/75290019-8a74d680-57ed-11ea-8e0f-0ba752d801fa.png)

**Comment by cyberalien** [comment]
Excellent!

I'm currently working on next iteration of Iconify, which is written in TypeScript. Unfortunately TypeScript uses `Object.assign` regardless of compile target and doesn't transpile it to anything else, so I'll just avoid using it. Compatibility with all users is more important than few saved bytes.

**Comment by bsolovij-ebsco** [comment]
@cyberalien - I would argue that you do not make concessions around your TS implementation. I would suggest that you major version the TS only / TS base (2.x instead of 1.x). Legacy support should be community driven and you should feel empowered to take your core project in the direction you see fit.

I realize this advice comes from the ether but Id be happy to help support backwards compatibility of newer iterations into ES5 compliant (or transpilable) code as much as possible to keep feature parity between the two.
